### ISSUE TITLE
Unable to Serialize XPathValue with JSON Serializer.

### ISSUE THREAD

**Issue by cssquirrel** [Offroadcode/Umbraco-Bulk-Edit#17]
@steroberts89 I'm encountering an error when testing the UmbracoBulkEdit package on the Chips Away website (on localhost) to confirm its working as intended.

When calling `GetPublishedContent()` for all frachisees under Home, I the error that says the JSON serializer is unable to serialize the xpathvalue. I'm having issues connecting the process to my Visual Studio debug on this project, so it's been difficult for me to debug, so I'm unsure exactly what part of the serialization is in error.
What I need to solve this is a way for us to process content like this with the JSON resolver, as near as I can tell.

Pete's asked me to stop trying to solve it on my end as I'm more or less stumped. Can you help so we can get this released?

Thanks!

**Comment by naepalm** [comment]
This was "fixed" by limiting the options for allowed fields to specific types in this commit: ca16c7b82e8f3ffa53b87f3bc88fadc1d9256506
