### ISSUE TITLE
Content types not loading

### ISSUE THREAD

**Issue by sotirisf** [Offroadcode/Umbraco-Bulk-Edit#20]
My content types dropdown comes out empty, containing only the default prompt.

Running the GetAllContentTypes (Umbraco/backoffice/ORCCsv/ContentType/getAll) method by itself, I get this wonderful error:
`{"Message":"An error has occurred.","ExceptionMessage":"A member with the name 'Name' already exists on 'Umbraco.Core.Models.ITemplate'. Use the JsonPropertyAttribute to specify another name.","ExceptionType":"Newtonsoft.Json.JsonSerializationException","StackTrace":"   at Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonProperty property)\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)\r\n   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray(JsonWriter writer, Object values, JsonArrayContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)\r\n   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)\r\n   at UmbracoBulkEdit.Controllers.ContentTypeController.buildSerializedResponse(Object objectToReturn)\r\n   at UmbracoBulkEdit.Controllers.ContentTypeController.GetAll()\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}`

I found that there is a reference to a similar serialization error here https://github.com/JamesNK/Newtonsoft.Json/issues/625 - but I'm not sure it's the same thing. 

Sorry for not providing any more information, I just thought it would be good to report this, haven't really looked deeper. 

The error occured on an Umbraco 7.5.11 installation which uses compositions for doctypes.

**Comment by PeteDuncanson** [comment]
Looks like you have a property called "Name" on your doctype which is causing the serialiser some issues as it already has a Name field on there. Thats just from reading the error message so might not be 100% correct.

Can you confirm if you have a doc type with a custom field called "Name" on it and if you are using Strongly Typed models (or Model Builder or similar). If you are using Strongly Typed models then can you cut and paste us in the Model with the "Name" field on it.

If find the class with the "Name" field (aka property) on it and you want to try a fix you can add an attribute to the class to rename it to something that won't clash:

```
[JsonProperty(PropertyName = "CustomerName")]
public string Name { get; set; }
```

Further details on various attributes here https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm

**Comment by sotirisf** [comment]
I don't have a "Name" property on any doctype (it would probably be an issue by itself, since IPublishedContent already contains a Name property). I do use ModelsBuilder. The problem is with Umbraco.Core.Models.ITemplate, which contains a property called "Name" as you can see here: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Models/ITemplate.cs  - the corresponding property on IPublishedContent is "defaultTemplate"

I'm curious as to why it throws an exception there, though, since that interface hasn't changed recently. I even tried to serialize the object specifying only a handful of properties, but I got the same error.

**Comment by PeteDuncanson** [comment]
Ok, lets do some simply sanity checking. What version of Umbraco are you running and are you running anything "crazy" code/package wise?

**Comment by sotirisf** [comment]
The Umbraco version I installed it on is 7.5.11.

All packages have been installed via Nuget. Apart from some cache-clearing events, nothing else crazy is going on. 

From the (very correct) way that you're handling this issue I can't help but suspect that it's "just me" that has this problem. If it is so, I could try installing it on a brand new Umbraco 7.5.11 and see if it has the same issues.

My packages.xml (deleted some common MS and Umbraco stuff in the middle to make it shorter):
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AutoMapper" version="3.3.1" targetFramework="net452" />
  <package id="ClientDependency" version="1.9.2" targetFramework="net452" />
  <package id="ClientDependency-Mvc5" version="1.8.0.0" targetFramework="net452" />
  <package id="Diplo.AuditLogViewer" version="1.0.1" targetFramework="net452" />
  <package id="Diplo.GodMode" version="1.3.7" targetFramework="net452" />
  <package id="DiploTraceLogViewer" version="2.3.2" targetFramework="net452" />
  <package id="DotSee.AutoNode" version="1.4.0" targetFramework="net452" />
  <package id="DotSee.VirtualNodes" version="1.0.3" targetFramework="net452" />
  <package id="Examine" version="0.1.81" targetFramework="net452" />
  <package id="HtmlAgilityPack" version="1.4.9" targetFramework="net452" />
  <package id="ImageProcessor" version="2.5.2" targetFramework="net452" />
  <package id="ImageProcessor.Web" version="4.8.2" targetFramework="net452" />
  <package id="ImageProcessor.Web.Config" version="2.3.0.0" targetFramework="net452" />
  <package id="jQuery" version="1.8.0" targetFramework="net452" />
  <package id="jQuery.Validation" version="1.8.0.1" targetFramework="net452" />
 ...
  <package id="Microsoft.IO.RecyclableMemoryStream" version="1.2.1" targetFramework="net452" />
  <package id="Microsoft.jQuery.Unobtrusive.Ajax" version="3.2.3" targetFramework="net452" />
  <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" targetFramework="net452" />
 ...
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />
  <package id="Nibble.Umbraco.ConfigTree" version="3.2.1" targetFramework="net452" />
  <package id="Nibble.Umbraco.UIOMatic" version="2.0.3" targetFramework="net452" />
  <package id="Nibble.Umbraco.UIOMatic.Core" version="2.0.3" targetFramework="net452" />
  <package id="Our.Umbraco.LinksPicker" version="1.0.1.0" targetFramework="net452" />
  <package id="Our.Umbraco.NestedContent" version="0.4.0" targetFramework="net452" />
  <package id="Our.Umbraco.Nexu" version="1.2.0" targetFramework="net452" />
  <package id="Our.Umbraco.UnVersion" version="2.1" targetFramework="net452" />
  <package id="Owin" version="1.0" targetFramework="net452" />
  <package id="RecaptchaNet" version="2.1.0" targetFramework="net452" />
  <package id="semver" version="1.1.2" targetFramework="net452" />
  <package id="SharpZipLib" version="0.86.0" targetFramework="net452" />
...
  <package id="Umbraco.ModelsBuilder" version="3.0.5" targetFramework="net452" />
  <package id="UmbracoCms" version="7.5.11" targetFramework="net452" />
  <package id="UmbracoCms.Core" version="7.5.11" targetFramework="net452" />
  <package id="UrlRewritingNet" version="2.0.7" targetFramework="net452" />
  <package id="uSync" version="3.3.4.740" targetFramework="net452" />
  <package id="uSync.Core" version="5.6.4.740" targetFramework="net452" />
  <package id="uWebSize" version="0.92" targetFramework="net452" />
  <package id="xmlrpcnet" version="2.5.0" targetFramework="net452" />
</packages>
```

**Comment by PeteDuncanson** [comment]
We've run it on something similar (maybe even older actually). Need to get it recreate-able really. Then we can do some digging.

BTW as stated in the readme this package serves our needs for our current client. Although we would love to make it amazing for all we can't fix everything. If we don't need it then we aren't going to fix it/develop it. Feel free to add what you need as we can't promise support/dev time. We will do what we can but don't wait on us I guess is the message ;)

**Comment by sotirisf** [comment]
Yes, of course, this goes without saying. I just wondered whether you had experienced this problem before, since it looked like it was coming from Umbraco itself and not from any later-added piece of code / package. Thank you for taking time to investigate this, I'll do some more digging myself and I'll be sure to let you know if I find something.

**Comment by sotirisf** [comment]
FYI, it was the NewtonSoft.JSon version. 7.0.1 seems to have an issue with serialization, I upgraded to the next version and everything worked.
